// Comprehensive Dataset for NexusLoot Daily Games
// Pokemon (Gen 1-4) & League of Legends Champions (All)

const POKEMON_DATA = [
  { "id": 1, "name": "Bulbasaur", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 0.7, "weight": 6.9 },
  { "id": 2, "name": "Ivysaur", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 1.0, "weight": 13.0 },
  { "id": 3, "name": "Venusaur", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 2.0, "weight": 100.0 },
  { "id": 4, "name": "Charmander", "gen": 1, "type1": "Fire", "type2": "None", "height": 0.6, "weight": 8.5 },
  { "id": 5, "name": "Charmeleon", "gen": 1, "type1": "Fire", "type2": "None", "height": 1.1, "weight": 19.0 },
  { "id": 6, "name": "Charizard", "gen": 1, "type1": "Fire", "type2": "Flying", "height": 1.7, "weight": 90.5 },
  { "id": 7, "name": "Squirtle", "gen": 1, "type1": "Water", "type2": "None", "height": 0.5, "weight": 9.0 },
  { "id": 8, "name": "Wartortle", "gen": 1, "type1": "Water", "type2": "None", "height": 1.0, "weight": 22.5 },
  { "id": 9, "name": "Blastoise", "gen": 1, "type1": "Water", "type2": "None", "height": 1.6, "weight": 85.5 },
  { "id": 10, "name": "Caterpie", "gen": 1, "type1": "Bug", "type2": "None", "height": 0.3, "weight": 2.9 },
  { "id": 11, "name": "Metapod", "gen": 1, "type1": "Bug", "type2": "None", "height": 0.7, "weight": 9.9 },
  { "id": 12, "name": "Butterfree", "gen": 1, "type1": "Bug", "type2": "Flying", "height": 1.1, "weight": 32.0 },
  { "id": 13, "name": "Weedle", "gen": 1, "type1": "Bug", "type2": "Poison", "height": 0.3, "weight": 3.2 },
  { "id": 14, "name": "Kakuna", "gen": 1, "type1": "Bug", "type2": "Poison", "height": 0.6, "weight": 10.0 },
  { "id": 15, "name": "Beedrill", "gen": 1, "type1": "Bug", "type2": "Poison", "height": 1.0, "weight": 29.5 },
  { "id": 16, "name": "Pidgey", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 0.3, "weight": 1.8 },
  { "id": 17, "name": "Pidgeotto", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 1.1, "weight": 30.0 },
  { "id": 18, "name": "Pidgeot", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 1.5, "weight": 39.5 },
  { "id": 19, "name": "Rattata", "gen": 1, "type1": "Normal", "type2": "None", "height": 0.3, "weight": 3.5 },
  { "id": 20, "name": "Raticate", "gen": 1, "type1": "Normal", "type2": "None", "height": 0.7, "weight": 18.5 },
  { "id": 21, "name": "Spearow", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 0.3, "weight": 2.0 },
  { "id": 22, "name": "Fearow", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 1.2, "weight": 38.0 },
  { "id": 23, "name": "Ekans", "gen": 1, "type1": "Poison", "type2": "None", "height": 2.0, "weight": 6.9 },
  { "id": 24, "name": "Arbok", "gen": 1, "type1": "Poison", "type2": "None", "height": 3.5, "weight": 65.0 },
  { "id": 25, "name": "Pikachu", "gen": 1, "type1": "Electric", "type2": "None", "height": 0.4, "weight": 6.0 },
  { "id": 26, "name": "Raichu", "gen": 1, "type1": "Electric", "type2": "None", "height": 0.8, "weight": 30.0 },
  { "id": 27, "name": "Sandshrew", "gen": 1, "type1": "Ground", "type2": "None", "height": 0.6, "weight": 12.0 },
  { "id": 28, "name": "Sandslash", "gen": 1, "type1": "Ground", "type2": "None", "height": 1.0, "weight": 29.5 },
  { "id": 29, "name": "Nidoran-F", "gen": 1, "type1": "Poison", "type2": "None", "height": 0.4, "weight": 7.0 },
  { "id": 30, "name": "Nidorina", "gen": 1, "type1": "Poison", "type2": "None", "height": 0.8, "weight": 20.0 },
  { "id": 31, "name": "Nidoqueen", "gen": 1, "type1": "Poison", "type2": "Ground", "height": 1.3, "weight": 60.0 },
  { "id": 32, "name": "Nidoran-M", "gen": 1, "type1": "Poison", "type2": "None", "height": 0.5, "weight": 9.0 },
  { "id": 33, "name": "Nidorino", "gen": 1, "type1": "Poison", "type2": "None", "height": 0.9, "weight": 19.5 },
  { "id": 34, "name": "Nidoking", "gen": 1, "type1": "Poison", "type2": "Ground", "height": 1.4, "weight": 62.0 },
  { "id": 35, "name": "Clefairy", "gen": 1, "type1": "Fairy", "type2": "None", "height": 0.6, "weight": 7.5 },
  { "id": 36, "name": "Clefable", "gen": 1, "type1": "Fairy", "type2": "None", "height": 1.3, "weight": 40.0 },
  { "id": 37, "name": "Vulpix", "gen": 1, "type1": "Fire", "type2": "None", "height": 0.6, "weight": 9.9 },
  { "id": 38, "name": "Ninetales", "gen": 1, "type1": "Fire", "type2": "None", "height": 1.1, "weight": 19.9 },
  { "id": 39, "name": "Jigglypuff", "gen": 1, "type1": "Normal", "type2": "Fairy", "height": 0.5, "weight": 5.5 },
  { "id": 40, "name": "Wigglytuff", "gen": 1, "type1": "Normal", "type2": "Fairy", "height": 1.0, "weight": 12.0 },
  { "id": 41, "name": "Zubat", "gen": 1, "type1": "Poison", "type2": "Flying", "height": 0.8, "weight": 7.5 },
  { "id": 42, "name": "Golbat", "gen": 1, "type1": "Poison", "type2": "Flying", "height": 1.6, "weight": 55.0 },
  { "id": 43, "name": "Oddish", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 0.5, "weight": 5.4 },
  { "id": 44, "name": "Gloom", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 0.8, "weight": 8.6 },
  { "id": 45, "name": "Vileplume", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 1.2, "weight": 18.6 },
  { "id": 46, "name": "Paras", "gen": 1, "type1": "Bug", "type2": "Grass", "height": 0.3, "weight": 5.4 },
  { "id": 47, "name": "Parasect", "gen": 1, "type1": "Bug", "type2": "Grass", "height": 1.0, "weight": 29.5 },
  { "id": 48, "name": "Venonat", "gen": 1, "type1": "Bug", "type2": "Poison", "height": 1.0, "weight": 30.0 },
  { "id": 49, "name": "Venomoth", "gen": 1, "type1": "Bug", "type2": "Poison", "height": 1.5, "weight": 12.5 },
  { "id": 50, "name": "Diglett", "gen": 1, "type1": "Ground", "type2": "None", "height": 0.2, "weight": 0.8 },
  { "id": 51, "name": "Dugtrio", "gen": 1, "type1": "Ground", "type2": "None", "height": 0.7, "weight": 33.3 },
  { "id": 52, "name": "Meowth", "gen": 1, "type1": "Normal", "type2": "None", "height": 0.4, "weight": 4.2 },
  { "id": 53, "name": "Persian", "gen": 1, "type1": "Normal", "type2": "None", "height": 1.0, "weight": 32.0 },
  { "id": 54, "name": "Psyduck", "gen": 1, "type1": "Water", "type2": "None", "height": 0.8, "weight": 19.6 },
  { "id": 55, "name": "Golduck", "gen": 1, "type1": "Water", "type2": "None", "height": 1.7, "weight": 76.6 },
  { "id": 56, "name": "Mankey", "gen": 1, "type1": "Fighting", "type2": "None", "height": 0.5, "weight": 28.0 },
  { "id": 57, "name": "Primeape", "gen": 1, "type1": "Fighting", "type2": "None", "height": 1.0, "weight": 32.0 },
  { "id": 58, "name": "Growlithe", "gen": 1, "type1": "Fire", "type2": "None", "height": 0.7, "weight": 19.0 },
  { "id": 59, "name": "Arcanine", "gen": 1, "type1": "Fire", "type2": "None", "height": 1.9, "weight": 155.0 },
  { "id": 60, "name": "Poliwag", "gen": 1, "type1": "Water", "type2": "None", "height": 0.6, "weight": 12.4 },
  { "id": 61, "name": "Poliwhirl", "gen": 1, "type1": "Water", "type2": "None", "height": 1.0, "weight": 20.0 },
  { "id": 62, "name": "Poliwrath", "gen": 1, "type1": "Water", "type2": "Fighting", "height": 1.3, "weight": 54.0 },
  { "id": 63, "name": "Abra", "gen": 1, "type1": "Psychic", "type2": "None", "height": 0.9, "weight": 19.5 },
  { "id": 64, "name": "Kadabra", "gen": 1, "type1": "Psychic", "type2": "None", "height": 1.3, "weight": 56.5 },
  { "id": 65, "name": "Alakazam", "gen": 1, "type1": "Psychic", "type2": "None", "height": 1.5, "weight": 48.0 },
  { "id": 66, "name": "Machop", "gen": 1, "type1": "Fighting", "type2": "None", "height": 0.8, "weight": 19.5 },
  { "id": 67, "name": "Machoke", "gen": 1, "type1": "Fighting", "type2": "None", "height": 1.5, "weight": 70.5 },
  { "id": 68, "name": "Machamp", "gen": 1, "type1": "Fighting", "type2": "None", "height": 1.6, "weight": 130.0 },
  { "id": 69, "name": "Bellsprout", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 0.7, "weight": 4.0 },
  { "id": 70, "name": "Weepinbell", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 1.0, "weight": 6.4 },
  { "id": 71, "name": "Victreebel", "gen": 1, "type1": "Grass", "type2": "Poison", "height": 1.7, "weight": 15.5 },
  { "id": 72, "name": "Tentacool", "gen": 1, "type1": "Water", "type2": "Poison", "height": 0.9, "weight": 45.5 },
  { "id": 73, "name": "Tentacruel", "gen": 1, "type1": "Water", "type2": "Poison", "height": 1.6, "weight": 55.0 },
  { "id": 74, "name": "Geodude", "gen": 1, "type1": "Rock", "type2": "Ground", "height": 0.4, "weight": 20.0 },
  { "id": 75, "name": "Graveler", "gen": 1, "type1": "Rock", "type2": "Ground", "height": 1.0, "weight": 105.0 },
  { "id": 76, "name": "Golem", "gen": 1, "type1": "Rock", "type2": "Ground", "height": 1.4, "weight": 300.0 },
  { "id": 77, "name": "Ponyta", "gen": 1, "type1": "Fire", "type2": "None", "height": 1.0, "weight": 30.0 },
  { "id": 78, "name": "Rapidash", "gen": 1, "type1": "Fire", "type2": "None", "height": 1.7, "weight": 95.0 },
  { "id": 79, "name": "Slowpoke", "gen": 1, "type1": "Water", "type2": "Psychic", "height": 1.2, "weight": 36.0 },
  { "id": 80, "name": "Slowbro", "gen": 1, "type1": "Water", "type2": "Psychic", "height": 1.6, "weight": 78.5 },
  { "id": 81, "name": "Magnemite", "gen": 1, "type1": "Electric", "type2": "Steel", "height": 0.3, "weight": 6.0 },
  { "id": 82, "name": "Magneton", "gen": 1, "type1": "Electric", "type2": "Steel", "height": 1.0, "weight": 60.0 },
  { "id": 83, "name": "Farfetch'd", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 0.8, "weight": 15.0 },
  { "id": 84, "name": "Doduo", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 1.4, "weight": 39.2 },
  { "id": 85, "name": "Dodrio", "gen": 1, "type1": "Normal", "type2": "Flying", "height": 1.8, "weight": 85.2 },
  { "id": 86, "name": "Seel", "gen": 1, "type1": "Water", "type2": "None", "height": 1.1, "weight": 90.0 },
  { "id": 87, "name": "Dewgong", "gen": 1, "type1": "Water", "type2": "Ice", "height": 1.7, "weight": 120.0 },
  { "id": 88, "name": "Grimer", "gen": 1, "type1": "Poison", "type2": "None", "height": 0.9, "weight": 30.0 },
  { "id": 89, "name": "Muk", "gen": 1, "type1": "Poison", "type2": "None", "height": 1.2, "weight": 30.0 },
  { "id": 90, "name": "Shellder", "gen": 1, "type1": "Water", "type2": "None", "height": 0.3, "weight": 4.0 },
  { "id": 91, "name": "Cloyster", "gen": 1, "type1": "Water", "type2": "Ice", "height": 1.5, "weight": 132.5 },
  { "id": 92, "name": "Gastly", "gen": 1, "type1": "Ghost", "type2": "Poison", "height": 1.3, "weight": 0.1 },
  { "id": 93, "name": "Haunter", "gen": 1, "type1": "Ghost", "type2": "Poison", "height": 1.6, "weight": 0.1 },
  { "id": 94, "name": "Gengar", "gen": 1, "type1": "Ghost", "type2": "Poison", "height": 1.5, "weight": 40.5 },
  { "id": 95, "name": "Onix", "gen": 1, "type1": "Rock", "type2": "Ground", "height": 8.8, "weight": 210.0 },
  { "id": 96, "name": "Drowzee", "gen": 1, "type1": "Psychic", "type2": "None", "height": 1.0, "weight": 32.4 },
  { "id": 133, "name": "Eevee", "gen": 1, "type1": "Normal", "type2": "None", "height": 0.3, "weight": 6.5 },
  { "id": 143, "name": "Snorlax", "gen": 1, "type1": "Normal", "type2": "None", "height": 2.1, "weight": 460.0 },
  { "id": 150, "name": "Mewtwo", "gen": 1, "type1": "Psychic", "type2": "None", "height": 2.0, "weight": 122.0 },
  { "id": 248, "name": "Tyranitar", "gen": 2, "type1": "Rock", "type2": "Dark", "height": 2.0, "weight": 202.0 },
  { "id": 249, "name": "Lugia", "gen": 2, "type1": "Psychic", "type2": "Flying", "height": 5.2, "weight": 216.0 },
  { "id": 384, "name": "Rayquaza", "gen": 3, "type1": "Dragon", "type2": "Flying", "height": 7.0, "weight": 206.5 },
  { "id": 445, "name": "Garchomp", "gen": 4, "type1": "Dragon", "type2": "Ground", "height": 1.9, "weight": 95.0 },
  { "id": 448, "name": "Lucario", "gen": 4, "type1": "Fighting", "type2": "Steel", "height": 1.2, "weight": 54.0 }
];

const LOL_DATA = [
  { "name": "Aatrox", "gender": "Male", "position": "Top", "species": "Darkin", "resource": "Blood Well", "year": 2013 },
  { "name": "Ahri", "gender": "Female", "position": "Mid", "species": "Vastaya", "resource": "Mana", "year": 2011 },
  { "name": "Akali", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Energy", "year": 2010 },
  { "name": "Akshan", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2021 },
  { "name": "Alistar", "gender": "Male", "position": "Support", "species": "Minotaur", "resource": "Mana", "year": 2009 },
  { "name": "Amumu", "gender": "Male", "position": "Jungle", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Anivia", "gender": "Female", "position": "Mid", "species": "Celestial", "resource": "Mana", "year": 2009 },
  { "name": "Annie", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Aphelios", "gender": "Male", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2019 },
  { "name": "Ashe", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Aurelion Sol", "gender": "Male", "position": "Mid", "species": "Celestial", "resource": "Mana", "year": 2016 },
  { "name": "Aurora", "gender": "Female", "position": "Mid", "species": "Vastaya", "resource": "Mana", "year": 2024 },
  { "name": "Azir", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2014 },
  { "name": "Bard", "gender": "Other", "position": "Support", "species": "Celestial", "resource": "Mana", "year": 2015 },
  { "name": "Bel'Veth", "gender": "Female", "position": "Jungle", "species": "Void-born", "resource": "None", "year": 2022 },
  { "name": "Blitzcrank", "gender": "Other", "position": "Support", "species": "Golem", "resource": "Mana", "year": 2009 },
  { "name": "Brand", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Braum", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2014 },
  { "name": "Briar", "gender": "Female", "position": "Jungle", "species": "Vampire", "resource": "Fury", "year": 2023 },
  { "name": "Caitlyn", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Camille", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2016 },
  { "name": "Cassiopeia", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Cho'Gath", "gender": "Male", "position": "Top", "species": "Void-born", "resource": "Mana", "year": 2009 },
  { "name": "Corki", "gender": "Male", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Darius", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Diana", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Dr. Mundo", "gender": "Male", "position": "Top", "species": "Human", "resource": "None", "year": 2009 },
  { "name": "Draven", "gender": "Male", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Ekko", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2015 },
  { "name": "Elise", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Evelynn", "gender": "Female", "position": "Jungle", "species": "Demon", "resource": "Mana", "year": 2009 },
  { "name": "Ezreal", "gender": "Male", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Fiddlesticks", "gender": "Other", "position": "Jungle", "species": "Demon", "resource": "Mana", "year": 2009 },
  { "name": "Fiora", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Fizz", "gender": "Male", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2011 },
  { "name": "Galio", "gender": "Male", "position": "Mid", "species": "Golem", "resource": "Mana", "year": 2010 },
  { "name": "Gangplank", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Garen", "gender": "Male", "position": "Top", "species": "Human", "resource": "None", "year": 2010 },
  { "name": "Gnar", "gender": "Male", "position": "Top", "species": "Yordle", "resource": "Rage", "year": 2014 },
  { "name": "Gragas", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Graves", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Gwen", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2021 },
  { "name": "Hecarim", "gender": "Male", "position": "Jungle", "species": "Undead", "resource": "Mana", "year": 2012 },
  { "name": "Heimerdinger", "gender": "Male", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Hwei", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2023 },
  { "name": "Illaoi", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2015 },
  { "name": "Irelia", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Ivern", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2016 },
  { "name": "Janna", "gender": "Female", "position": "Support", "species": "Spirit", "resource": "Mana", "year": 2009 },
  { "name": "Jarvan IV", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Jax", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Jayce", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Jhin", "gender": "Male", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2016 },
  { "name": "Jinx", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2013 },
  { "name": "Kai'Sa", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2018 },
  { "name": "Kalista", "gender": "Female", "position": "ADC", "species": "Undead", "resource": "Mana", "year": 2014 },
  { "name": "Karma", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Karthus", "gender": "Male", "position": "Jungle", "species": "Undead", "resource": "Mana", "year": 2009 },
  { "name": "Kassadin", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Katarina", "gender": "Female", "position": "Mid", "species": "Human", "resource": "None", "year": 2009 },
  { "name": "Kayle", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Kayn", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2017 },
  { "name": "Kennen", "gender": "Male", "position": "Top", "species": "Yordle", "resource": "Energy", "year": 2010 },
  { "name": "Kha'Zix", "gender": "Male", "position": "Jungle", "species": "Void-born", "resource": "Mana", "year": 2012 },
  { "name": "Kindred", "gender": "Other", "position": "Jungle", "species": "Celestial", "resource": "Mana", "year": 2015 },
  { "name": "Kled", "gender": "Male", "position": "Top", "species": "Yordle", "resource": "Courage", "year": 2016 },
  { "name": "Kog'Maw", "gender": "Male", "position": "ADC", "species": "Void-born", "resource": "Mana", "year": 2010 },
  { "name": "K'Sante", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2022 },
  { "name": "LeBlanc", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Lee Sin", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Energy", "year": 2011 },
  { "name": "Leona", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Lillia", "gender": "Female", "position": "Jungle", "species": "Vastaya", "resource": "Mana", "year": 2020 },
  { "name": "Lissandra", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2013 },
  { "name": "Lucian", "gender": "Male", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2013 },
  { "name": "Lulu", "gender": "Female", "position": "Support", "species": "Yordle", "resource": "Mana", "year": 2012 },
  { "name": "Lux", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Malphite", "gender": "Male", "position": "Top", "species": "Golem", "resource": "Mana", "year": 2009 },
  { "name": "Malzahar", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Maokai", "gender": "Male", "position": "Support", "species": "Spirit", "resource": "Mana", "year": 2011 },
  { "name": "Master Yi", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Milio", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2023 },
  { "name": "Miss Fortune", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Wukong", "gender": "Male", "position": "Top", "species": "Vastaya", "resource": "Mana", "year": 2011 },
  { "name": "Mordekaiser", "gender": "Male", "position": "Top", "species": "Undead", "resource": "Shield", "year": 2010 },
  { "name": "Morgana", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Naafiri", "gender": "Female", "position": "Mid", "species": "Darkin", "resource": "Mana", "year": 2023 },
  { "name": "Nami", "gender": "Female", "position": "Support", "species": "Vastaya", "resource": "Mana", "year": 2012 },
  { "name": "Nasus", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Nautilus", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Neeko", "gender": "Female", "position": "Support", "species": "Vastaya", "resource": "Mana", "year": 2018 },
  { "name": "Nidalee", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Nilah", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2022 },
  { "name": "Nocturne", "gender": "Other", "position": "Jungle", "species": "Demon", "resource": "Mana", "year": 2011 },
  { "name": "Nunu & Willump", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Olaf", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Orianna", "gender": "Female", "position": "Mid", "species": "Golem", "resource": "Mana", "year": 2011 },
  { "name": "Ornn", "gender": "Male", "position": "Top", "species": "Celestial", "resource": "Mana", "year": 2017 },
  { "name": "Pantheon", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Poppy", "gender": "Female", "position": "Top", "species": "Yordle", "resource": "Mana", "year": 2010 },
  { "name": "Pyke", "gender": "Male", "position": "Support", "species": "Undead", "resource": "Mana", "year": 2018 },
  { "name": "Qiyana", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2019 },
  { "name": "Quinn", "gender": "Female", "position": "Top", "species": "Human", "resource": "Mana", "year": 2013 },
  { "name": "Rakan", "gender": "Male", "position": "Support", "species": "Vastaya", "resource": "Mana", "year": 2017 },
  { "name": "Rammus", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Rek'Sai", "gender": "Female", "position": "Jungle", "species": "Void-born", "resource": "Rage", "year": 2014 },
  { "name": "Rell", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2020 },
  { "name": "Renata Glasc", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2022 },
  { "name": "Renekton", "gender": "Male", "position": "Top", "species": "Human", "resource": "Fury", "year": 2011 },
  { "name": "Rengar", "gender": "Male", "position": "Jungle", "species": "Vastaya", "resource": "Ferocity", "year": 2012 },
  { "name": "Riven", "gender": "Female", "position": "Top", "species": "Human", "resource": "None", "year": 2011 },
  { "name": "Rumble", "gender": "Male", "position": "Top", "species": "Yordle", "resource": "Heat", "year": 2011 },
  { "name": "Ryze", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Samira", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2020 },
  { "name": "Sejuani", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Senna", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2019 },
  { "name": "Seraphine", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2020 },
  { "name": "Sett", "gender": "Male", "position": "Top", "species": "Human", "resource": "Grit", "year": 2020 },
  { "name": "Shaco", "gender": "Male", "position": "Jungle", "species": "Demon", "resource": "Mana", "year": 2009 },
  { "name": "Shen", "gender": "Male", "position": "Top", "species": "Human", "resource": "Energy", "year": 2010 },
  { "name": "Shyvana", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Fury", "year": 2011 },
  { "name": "Singed", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Sion", "gender": "Male", "position": "Top", "species": "Undead", "resource": "Mana", "year": 2009 },
  { "name": "Sivir", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Skarner", "gender": "Male", "position": "Jungle", "species": "Brackern", "resource": "Mana", "year": 2011 },
  { "name": "Smolder", "gender": "Male", "position": "ADC", "species": "Dragon", "resource": "Mana", "year": 2024 },
  { "name": "Sona", "gender": "Female", "position": "Support", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Soraka", "gender": "Female", "position": "Support", "species": "Celestial", "resource": "Mana", "year": 2009 },
  { "name": "Swain", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Sylas", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2019 },
  { "name": "Syndra", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Tahm Kench", "gender": "Male", "position": "Support", "species": "Demon", "resource": "Mana", "year": 2015 },
  { "name": "Taliyah", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2016 },
  { "name": "Talon", "gender": "Male", "position": "Assassin", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Taric", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Teemo", "gender": "Male", "position": "Top", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Thresh", "gender": "Male", "position": "Support", "species": "Undead", "resource": "Mana", "year": 2013 },
  { "name": "Tristana", "gender": "Female", "position": "ADC", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Trundle", "gender": "Male", "position": "Jungle", "species": "Troll", "resource": "Mana", "year": 2010 },
  { "name": "Tryndamere", "gender": "Male", "position": "Top", "species": "Human", "resource": "Fury", "year": 2009 },
  { "name": "Twisted Fate", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Twitch", "gender": "Male", "position": "ADC", "species": "Rat", "resource": "Mana", "year": 2009 },
  { "name": "Udyr", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Urgot", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Varus", "gender": "Male", "position": "ADC", "species": "Darkin", "resource": "Mana", "year": 2012 },
  { "name": "Vayne", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Veigar", "gender": "Male", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2009 },
  { "name": "Vel'Koz", "gender": "Male", "position": "Mid", "species": "Void-born", "resource": "Mana", "year": 2014 },
  { "name": "Vex", "gender": "Female", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2021 },
  { "name": "Vi", "gender": "Female", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2012 },
  { "name": "Viego", "gender": "Male", "position": "Jungle", "species": "Undead", "resource": "None", "year": 2021 },
  { "name": "Viktor", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Vladimir", "gender": "Male", "position": "Mid", "species": "Human", "resource": "None", "year": 2010 },
  { "name": "Volibear", "gender": "Male", "position": "Jungle", "species": "Celestial", "resource": "Mana", "year": 2011 },
  { "name": "Warwick", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Xayah", "gender": "Female", "position": "ADC", "species": "Vastaya", "resource": "Mana", "year": 2017 },
  { "name": "Xerath", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Xin Zhao", "gender": "Male", "position": "Jungle", "species": "Human", "resource": "Mana", "year": 2010 },
  { "name": "Yasuo", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Flow", "year": 2013 },
  { "name": "Yone", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Flow", "year": 2020 },
  { "name": "Yorick", "gender": "Male", "position": "Top", "species": "Human", "resource": "Mana", "year": 2011 },
  { "name": "Yuumi", "gender": "Female", "position": "Support", "species": "Cat", "resource": "Mana", "year": 2019 },
  { "name": "Zac", "gender": "Male", "position": "Jungle", "species": "Golem", "resource": "None", "year": 2013 },
  { "name": "Zed", "gender": "Male", "position": "Mid", "species": "Human", "resource": "Energy", "year": 2012 },
  { "name": "Zeri", "gender": "Female", "position": "ADC", "species": "Human", "resource": "Mana", "year": 2022 },
  { "name": "Ziggs", "gender": "Male", "position": "Mid", "species": "Yordle", "resource": "Mana", "year": 2012 },
  { "name": "Zilean", "gender": "Male", "position": "Support", "species": "Human", "resource": "Mana", "year": 2009 },
  { "name": "Zoe", "gender": "Female", "position": "Mid", "species": "Human", "resource": "Mana", "year": 2017 },
  { "name": "Zyra", "gender": "Female", "position": "Support", "species": "Plant", "resource": "Mana", "year": 2012 }
];

const WORDLE_WORDS = [
  "STEAM", "SPAWN", "CRAFT", "MANA", "QUEST", 
  "ARMOR", "SKILL", "LEVEL", "EQUIP", "BOSS", 
  "LOOT", "GRIND", "FRAG", "AGGRO", "NOOB",
  "PATCH", "STUN", "GUILD", "READY", "PIXEL",
  "COMBO", "DRAIN", "POWER", "TIMER", "SMITE"
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { POKEMON_DATA, LOL_DATA, WORDLE_WORDS };
}
